initalize visualization grafana plugin
dyc3/opentogethertube pull request #1244
Opened 2024-01-21 18:30 UTC by cjrkoa

Grafana strongly recommends creating a new repo and when I try to run it just launches OTT. It might be better to just make a new repository for this

2024-01-21 18:38 UTC, dyc3 commented
> when I try to run it just launches OTT

That's because this is a monorepo. The commands will work if you cd into the directory with the `package.json`. It needs to be added to the workspace packages. Read https://classic.yarnpkg.com/lang/en/docs/workspaces/

2024-01-21 18:46 UTC, dyc3 requested changes
Please move the package to `packages/`, like I asked in the previous PR. Other than that, this is fine.

2024-01-21 18:46 UTC, dyc3 commented on balancer-visualization-prototype/ott-visualizationprototype-panel/package.json
> +  "name": "visualization-prototype",
nit: Why'd you call it prototype? This is the permanent name of the package. Please make it something short, like `ott-vis`.

2024-01-21 18:46 UTC, dyc3 commented on balancer-visualization-prototype/ott-visualizationprototype-panel/LICENSE
Remove this

2024-01-22 13:13 UTC, dyc3 requested changes
I have no idea why you moved it to `crates`, that's for rust crates, which this is not. Please move it to `packages/` and fix the folder structure so that the name of the package's folder matches the name of the package, and so that the package is not double nested. The full path to the `package.json` should be `packages/ott-vis/package.json`.

Also, you still need to add the package to the workspace in the root `package.json`.

2024-01-22 13:13 UTC, dyc3 commented on crates/ott-balancer-visualization/ott-visualizationprototype-panel/package.json
> +  "name": "ott-visualization",
Please name this `ott-vis`. I do not want to type out this big long name every time I need to.

2024-01-22 15:59 UTC, cjrkoa commented
> I have no idea why you moved it to `crates`, that's for rust crates, which this is not. Please move it to `packages/` and fix the folder structure so that the name of the package's folder matches the name of the package, and so that the package is not double nested. The full path to the `package.json` should be `packages/ott-vis/package.json`.
> 
> Also, you still need to add the package to the workspace in the root `package.json`.

I didn't see a packages folder and figured you meant crates. My bad

2024-01-22 16:23 UTC, dyc3 requested changes

2024-01-22 16:23 UTC, dyc3 commented on package.json
> +    "ott-vis"
it needs to be the full path from the root of the repo
```suggestion
    "packages/ott-vis"
```

2024-01-22 16:24 UTC, dyc3 approved these changes

2024-01-22 16:43 UTC, dyc3 commented
@coderabbitai Open an issue for updating the CI pipelines to add this package, and the release pipelines to sign the plugin

2024-01-22 17:44 UTC, merged