client: switch to locally hosted fonts
dyc3/opentogethertube pull request #1273
Opened 2024-01-27 16:27 UTC by NickSlowinski

Hi there,
this PR fixes #1260 and the related discussion #1259.

All current fonts (including the Material Icons fallback) are now locally served.
Please note, that only used fonts are included (Latin and Cyrillic) - fonts for Vietnamese and Greek (which were previously loaded by Google Fonts) are _no longer_ included.

A test image can be found [here](https://quay.io/repository/nickslowinski/opentogethertube-fonts-pr) - or just use `quay.io/nickslowinski/opentogethertube-fonts-pr@sha256:0540120ff12141b926f539e61ca611eef00c4d3721d709b0bba07db7fefdebaa` in the `docker-compose.yml`.

Side note:
Please be aware that your base images to build the docker image are ancient (they are based on Alpine 3.16) and won't get all updates, hence the security warnings at Quay.

2024-01-27 17:06 UTC, dyc3 requested changes
Thanks for the PR! The missing Vietnamese and Greek glyphs shouldn't be an issue for now.

These fonts need to go in `client/src/assets/fonts`.

2024-01-27 17:06 UTC, dyc3 commented on client/index.html
> +  <link rel="stylesheet" href="/fonts.css">
This should be imported in `App.vue`, and it should be a `.scss` file.

2024-01-27 17:09 UTC, NickSlowinski commented on client/fonts.css
I have tested it in 'client/src', but your Dockerfile deletes this path in the final build. I can edit your Dockerfile to ignore these, but I chose to modify as little as possible at your code.

2024-01-27 17:13 UTC, dyc3 commented on client/fonts.css
That's because it needs to be imported by vue code in order for the bundler to pick it up.

2024-01-27 17:26 UTC, NickSlowinski commented on client/fonts.css
Got it, I will be fixing this later - I did not look at the code too closely at first and did not touch Vue until now.

2024-01-28 14:26 UTC, NickSlowinski commented
Every requested change should be addressed now.

2024-01-28 19:05 UTC, dyc3 reviewed
This looks good. Once my Internet comes back I'll do a proper review

2024-01-28 21:18 UTC, dyc3 approved these changes

2024-01-28 21:52 UTC, merged