make monolith ids constant
dyc3/opentogethertube pull request #1287
Opened 2024-01-30 22:32 UTC by Victor-M-Giraldo

- closes 1251

2024-01-30 22:43 UTC, dyc3 commented
Yeah that sounds right

2024-01-30 23:09 UTC, Victor-M-Giraldo commented
How is the id defined in the constructor for `BalancerConnection` any different than a `MonolithID`?

Also, is there an example somewhere in the code of reading the payload, or how would I access that id to use in `connection.rs` rather than generating it in there?

2024-01-30 23:17 UTC, dyc3 commented on server/balancer.ts
> +				id: uuidv4(),
This still makes the id random for every balancer it connects to. It needs to be constant across reconnects. It's ok if the id is not constant across service restarts (eg don't store it in a file, it being a global is fine).

2024-02-01 21:32 UTC, dyc3 commented on crates/ott-balancer/src/connection.rs
> +        let id_clone;
nit: 
```suggestion
        let monolith_id;
```

2024-02-03 05:44 UTC, Victor-M-Giraldo commented
Having some trouble writing the test for this. Might ask for help tomorrow.

2024-02-03 10:31 UTC, dyc3 commented
The most valuable test here would probably be a unit test in `clientmanager.spec.ts` that creates 2 `BalancerConnectionMock` and see if they both get sent the same id.

2024-02-04 20:46 UTC, Victor-M-Giraldo commented
How can I run only tests for a certain file? Is that possible?

2024-02-04 21:17 UTC, dyc3 commented
Yeah should be possible. Look up the docs for `jest` or `cargo test`, depending if you're working with ts or rust, respectively. I can never get it to work reliably with jest

2024-02-04 21:28 UTC, Victor-M-Giraldo commented
Sounds good. I'll take a look. Just want to make sure the test is working without running the entire suite.

Also, the monolith IDS should be different, correct?

2024-02-04 22:07 UTC, dyc3 commented
Monolith ids should be the same within the context of the monolith. Across multiple monoliths, their ids should be different.

2024-02-04 22:26 UTC, Victor-M-Giraldo commented
Okay, that's what I thought.

2024-02-05 02:38 UTC, Victor-M-Giraldo commented
Figure this probably isn't what you mean. 

Is it something to do with `sendMock`?

2024-02-05 03:02 UTC, dyc3 commented on server/tests/unit/clientmanager.spec.ts
> +	it("should have unique IDS for each instance of a monolith", () => {
From this context, there is only 1 monolith: the one that is running. The client manager should send the same id to both of these mock connections.

2024-02-05 04:51 UTC, Victor-M-Giraldo commented
I only see stuff about the client ID there. Or is that what you meant?

2024-02-05 12:53 UTC, dyc3 commented
No, I'm not talking about the client id, I'm talking about the goal of this pr.

2024-02-05 13:22 UTC, Victor-M-Giraldo commented
Alright.

2024-02-06 00:41 UTC, Victor-M-Giraldo commented
Think that works.

2024-02-06 00:46 UTC, dyc3 requested changes

2024-02-06 00:46 UTC, dyc3 commented on server/tests/unit/clientmanager.spec.ts
> +			.payload.id;
this is filtering the wrong one. you need to filter the calls, not the call arguments

2024-02-06 00:50 UTC, dyc3 commented on server/tests/unit/clientmanager.spec.ts
> +			.payload.id;
It's ok to leave it the way it was

2024-02-06 01:42 UTC, dyc3 commented
if you want to rebase on master, I just pushed a commit that adds type annotations to `sendMock`

2024-02-06 19:53 UTC, dyc3 requested changes

2024-02-06 19:53 UTC, dyc3 commented on server/tests/unit/clientmanager.spec.ts
> +	});
this should also assert that id1 and id2 are both not undefined

2024-02-06 22:12 UTC, dyc3 approved these changes

2024-02-06 22:13 UTC, merged