Add unit tests for ott-vis-datasource and ott-collector communication
dyc3/opentogethertube pull request #1435
Opened 2024-03-01 21:43 UTC by cjrkoa

Fixes #1409

2024-03-02 00:29 UTC, dyc3 requested changes

2024-03-02 00:29 UTC, dyc3 commented on packages/ott-vis-datasource/src/datasource.test.ts
It looks like you're trying to write a unit test for the datasource. This is clearly going to end up creating more code than you're testing, which in my eyes is a code smell. Like I said before, the datasource doesn't really do any processing. There's nothing really to unit test in this package.

If anything, what you should be writing to test this package is a cypress e2e test, where you can assert that it makes an outbound request. I don't want to test implementation details.

2024-03-03 17:56 UTC, cjrkoa commented on packages/ott-vis-datasource/src/datasource.test.ts
@dyc3 The way I'm reading this/interpreting tone suggests that #1409 isn't a necessary task for this sprint, am I correct? (I can still write a cypress e2e test if you think it's needed)

2024-03-03 19:16 UTC, dyc3 commented on packages/ott-vis-datasource/src/datasource.test.ts
Lets stick to just the cypress test. It would be nice to have a smoke test. You just need to assert that it makes an outbound request.

2024-03-23 14:13 UTC, dyc3 commented
closing in favor of #1558

2024-03-23 14:13 UTC, closed without merging