client ids system state
dyc3/opentogethertube pull request #1581
Opened 2024-03-29 19:23 UTC by Victor-M-Giraldo

- closes #1562

2024-03-29 19:26 UTC, Victor-M-Giraldo commented
Still need to actually fix the tests.

2024-03-29 20:21 UTC, dyc3 reviewed
Looking good so far.

2024-03-29 20:21 UTC, dyc3 commented on packages/ott-vis-panel/src/components/TreeDisplay.tsx
>  						id: `${room.name}-${index}`,
This needs to become the client id

2024-03-29 20:21 UTC, dyc3 commented on packages/ott-vis-panel/src/components/TreeDisplay.tsx
> +				children: Array.from({ length: room.clients.length }, (_, index) => {
this `Array.from` hack can be removed in favor of a `.map` or something more readable.

2024-03-31 18:22 UTC, Victor-M-Giraldo commented
Don't know if the unit test is really necessary, but I think this ones good.

2024-03-31 18:53 UTC, dyc3 requested changes
This is good for `ott-vis-panel`, but `ott-collector` and `ott-balancer` still need to be updated accordingly.

Currently, it seems like the interop between the collector and the panel isn't being enforced in CI.

2024-03-31 20:01 UTC, dyc3 commented
You should rebase this PR for better type checking

2024-04-03 03:59 UTC, dyc3 commented
Whoops, I made some changes earlier today that are conflicting. Sorry about that, I can rebase this for you if you want

2024-04-03 17:09 UTC, Victor-M-Giraldo commented
> Whoops, I made some changes earlier today that are conflicting. Sorry about that, I can rebase this for you if you want

Yeah, sure. I tried to do it myself. There is only one conflict but the incoming change is an older version of the `buildMonolithTrees` which I don't get why.

2024-04-03 18:21 UTC, Victor-M-Giraldo commented
Since `countRoomClients` is returning a map of names to number of clients, I don't think I can access the id for the RegionView and GlobalView.

2024-04-03 18:59 UTC, dyc3 approved these changes
Yeah don't worry about global/region view. We're probably going to trash them.

2024-04-03 19:00 UTC, merged

2024-04-03 19:01 UTC, Victor-M-Giraldo commented
Okay, but say if you did want to do that would you change `countRoomClients` to be like `Record<string, ClientState[]` or something.

2024-04-03 19:43 UTC, dyc3 commented
I would probably leave that count function as is and create a new one.